[package]
name = "calc-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
actix-web = "3"
serde = "1"
serde_json = "1"
derive_more = "0.99.0"

[dev-dependencies]
rstest = "0.12.0"